### ISSUE TITLE
EP01 - ArBC

### ISSUE THREAD

**Issue by Eduardolimr** [fga-eps-mds/2019.2-ArBC#13]
## Descrição
Eu, como Educador, desejo que aplicação identifique uma palavra e mostre uma imagem correspondente por meio de realidade aumentada.

## Critérios de Aceitação
- [x] Identificar letras
- [x] Identificar palavra como conjunto de letras
- [x] Verificar existência da palavra no banco de dados
- [x] Mostrar imagem correspondente usando API de Realidade Aumentada

## Comportamento esperado
Ao apontar a câmera para um conjunto de letras, formar uma palavra e mostrar sua imagem correspondente (caso exista) por meio de realidade aumentadada.
